---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Catherine Johnston"
pagetitle: "PM1 Catherine Johnston"
date: "November 3, 2024"

format:
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

[Catherine's GitHub Repo](https://github.com/ccjohnston1/final-project-1.git)

:::

## Data source

Movies dataset^[https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?select=movies_metadata.csv. Accessed Nov 3, 2024]

This data set contains 24 variables and 45,466 observations. It takes a look at films released on or before July of 2017 and lists certain aspects of the film, like its original language, where it was filmed, average ratings, budget, revenue, etc. Average ratings of the movies listed are on a scale from 1-5, and were obtained from the official GroupLens website. There are 26 million individual ratings from 270,000 users for all 45,000 movies that have been averaged out for each film. This data set is a collaboration of a bunch of smaller data sets, all examining different aspects of the 45,000 movies. All 6 smaller data sets have been combined together to create the data set I am using for this project. 


## Why this data

I am really interested in working with movie data, and I thought this would be a wonderful opportunity to do so. I love the arts and am a music major myself, so I thought this was a great opportunity to combine art and data science! I am really interested to see how different variables correlate with one another, or if certain genres generally receive higher average ratings than others. Personally, I am a huge horror movie fan, but I always tend to see that horror movies receive lower ratings (despite how good the film actually is) on movie rating sites. I am curious to see if this is true. I want to check whether the movies with the lowest ratings are horror, or if it is just a coincidence! ^[https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset?select=movies_metadata.csv. Accessed Nov 3, 2024]

## Data quality & complexity check

```{r}
#| label: data-source-load
#| echo: false

#load tidyverse
library(tidyverse)
library(naniar)

#read data in and assign to new name
movies_data <- read.csv(file = "data/movies_metadata.csv")

#summary
movies_data |>
  skimr:: skim() |>
  knitr:: kable()

#variables missing
 movies_data |>
  gg_miss_var()

#variable count 
movies_data |>
  miss_var_summary() |>
  filter(n_miss > 0) |>
  knitr:: kable()

```

I have 24 variables and 45,466 observations. I am working with 20 character variables, 4 numeric variables (including the release date variable which is formatted as a string). This dataset is pretty tidy! There are 263 missing run time values, but in the grand scheme of things, that is not significant at all. There are also 6 values missing for revenue, vote average and vote count. These are not significant at all, so I am working with a pretty clean dataset.

## Potential data issues

I can't think of any major issues right now. Like I said, this data is pretty clean, so I think most of my project will be focused around EDA which I am looking forward to. There really are no significant missing values, so I am covered in the missingness department. I am going to keep an eye out for any outliers though, like unusually high or low revenues/budgets. Some of these movies were produced before the year 2000, so I will need to think about inflation levels with those values if they happen to be outliers.

## Misc

I want to see if there is a correlation between movie runtimes and ratings. Do longer movies receive lower ratings because people get tired of watching? I also want to look into budgets and if those affect ratings. Do people tend to rate higher budget movies better than lower budget movies? Also, do the ratings affect the popularity levels of the movie? All things to consider going into this project!
